apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: playlist-recommender-system-persistent-volume-claim
  namespace: antoniolima
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: antoniolima
  storageClassName: default-storage-class-antoniolima
